#!/bin/python3

# fix_myid
#
# This is a command line tool to fix an incorrect myid field
# I was going to add this as a dialog/feature to the GUI,
# but I decided it was so infrequent that it could just
# be handled via a command line tool like this.
#
# Tom Trebisky  7-30-2024

from Micros import *

m = Micros ()

# m.update_one ( 274, "myid", "08-144" )
m.update_one ( 380, "myid", "08-249" )
m.update_one ( 381, "myid", "08-250" )
m.update_one ( 382, "myid", "08-251" )
m.update_one ( 383, "myid", "08-252" )

m.close ()

# THE END
