#!/bin/python3

# labels
#
# This is a command line tool to generate sheets of labels.
# The argument list can be any number of ID for which labels
# are desired.  The sheet will be filled following the last
# label in that list.
#
# Tom Trebisky  7-23-2024

import sys
import os

from Micros import Micros
from Labels import Labelsheet

#my_path = Micros.grog_path ()
#print ( "Running: ", my_path )

id_list = []

if len(sys.argv) <= 1 :
    id_list.append ( "08-149" )
else :
    for id in sys.argv[1:] :
        id_list.append ( id )

#for x in id_list :
#    print ( x )

m = Micros ()
#m.get_all ()

#mm = m.lookup ( id )
#print ( mm )

#hh = m.get_hash ( id )
#print ( hh )

print ( "Start sheet with: ", id )
labs = m.mk_label ( id_list, 80 )
if labs == None :
    print ( "Cannot find starting ID" )
    exit ()

n = len(labs)
print ( n, " labels generated" )

#for l in labs :
#    print ( l )

m.close ()

if labs == None :
    print ( "Could not find: ", id )
    exit ()

ll = Labelsheet ()
ll.sheet ( labs )

# THE END
