#!/bin/python3

# count
#
# This is a command line tool to give me statistics
# from my micromount database.
# In particular, a count of how many of each species I have.
#
# run the result through sort:
#
#  ./count | sort -rn | head -20
#
# Tom Trebisky  7-26-2024

import sys
import os
import re

from Micros import *

mdb = Micros ()
data = mdb.all()
mdb.close ()

counts = {}
for m in data :
    species = m[m_SPECIES]
    species = re.sub ( r'^\s*', '', species )
    species = re.sub ( r'\s+.*', '', species )
    # print ( species )
    sw = species.split ()
    if len(sw) > 1 :
        print ( "Trouble: ", species )
    if species in counts :
        counts[species] += 1
    else:
        counts[species] = 1

print ( len(data), " mounts" )
print ( len(counts), " species" )

tmp = "zzz"
os.system ( f"rm -f {tmp}" )
with open ( tmp, "w" ) as f:
    for s in counts :
        f.write ( f"{counts[s]} {s}\n" )

os.system ( f"sort -rn {tmp} | head -20" )
os.system ( f"rm -f {tmp}" )

# THE END
